name: Run_Scripts
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install Puppeteer's Browser
        run: npx puppeteer browsers install chrome
      - name: Install Puppeteer Dependencies
        run: |
              sudo apt-get update
              sudo apt-get install -y \
              libnss3 \
              libatk1.0-0 \
              libatk-bridge2.0-0 \
              libcups2 \
              libxcomposite1 \
              libxrandr2 \
              libxdamage1 \
              libxfixes3 \
              libgbm1 \
              libpango-1.0-0 \
              libasound2 \
              libwayland-client0 \
              libwayland-cursor0 \
              libwayland-egl1 \
              libgdk-pixbuf2.0-0 \
              libx11-xcb1 \
              libdbus-glib-1-2 \
              libxkbcommon-x11-0
      - name: Run Devjobs script
        run: node ./scripts/devjobs-processing-script.js 
      - name: Run Juniors script
        run: node ./scripts/juniors-scraping-script.js 
      - name: Run Ejobs script with timeout
        run: timeout 60s node ./scripts/ejobs-scraping-script.js || echo "Ejobs script timed out after 1 minute"


        
        
  
